/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Reply {
    id: bigint;
    content: string;
    createdAt: bigint;
    authorName: string;
    postId: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface HelpRequest {
    id: bigint;
    status: string;
    applicantName: string;
    contactInfo: string;
    createdAt: bigint;
    description: string;
    requestType: string;
}
export type PersonId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DonationChannel {
    id: bigint;
    wechatPayQr?: string;
    channelName: string;
    createdAt: bigint;
    instructions?: string;
    bankName?: string;
    accountName?: string;
    accountNumber?: string;
    alipayQr?: string;
}
export interface ClanContact {
    id: bigint;
    contactType: string;
    name: string;
    createdAt: bigint;
    role: string;
    email?: string;
    address?: string;
    notes?: string;
    phone?: string;
    wechat?: string;
}
export interface ActivityImage {
    id: bigint;
    data: Uint8Array;
    activityId: bigint;
    mimeType: string;
    fileName: string;
    uploadedAt: bigint;
}
export interface Activity {
    id: bigint;
    title: string;
    createdAt: bigint;
    description: string;
    eventDate: string;
}
export interface ManuscriptEntry {
    id: string;
    blob: ExternalBlob;
    description: string;
    fileName: string;
    uploadDate: Time;
}
export interface Post {
    id: bigint;
    content: string;
    createdAt: bigint;
    authorName: string;
}
export interface Person {
    id: PersonId;
    country?: string;
    province?: string;
    deathDate?: string;
    birthDate?: string;
    city?: string;
    profilePhoto?: ExternalBlob;
    biography: string;
    generationNumber: bigint;
    fullName: string;
    siblings: Array<PersonId>;
    nationality?: string;
    children: Array<PersonId>;
    gender?: string;
    mother: string;
    mediaFiles: Array<ExternalBlob>;
    father: string;
}
export interface UserProfile {
    name: string;
}
export interface Relationship {
    id: bigint;
    createdAt: Time;
    person1Id: PersonId;
    person2Id: PersonId;
    relationshipType: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMediaFile(personId: PersonId, file: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addRelationship(person1Id: PersonId, person2Id: PersonId, relationshipType: string): Promise<void>;
    addReply(postId: bigint, authorName: string, content: string): Promise<{
        __kind__: "ok";
        ok: Reply;
    } | {
        __kind__: "err";
        err: string;
    }>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createActivity(title: string, eventDate: string, description: string): Promise<{
        __kind__: "ok";
        ok: Activity;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createClanContact(contactType: string, name: string, role: string, phone: string | null, email: string | null, wechat: string | null, address: string | null, notes: string | null): Promise<{
        __kind__: "ok";
        ok: ClanContact;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createDonationChannel(channelName: string, accountName: string | null, accountNumber: string | null, bankName: string | null, wechatPayQr: string | null, alipayQr: string | null, instructions: string | null): Promise<{
        __kind__: "ok";
        ok: DonationChannel;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createPerson(fullName: string, generationNumber: bigint, father: string, mother: string, bio: string, photo: ExternalBlob | null, gender: string | null, birthDate: string | null, deathDate: string | null, country: string | null, province: string | null, city: string | null, nationality: string | null): Promise<{
        __kind__: "ok";
        ok: PersonId;
    }>;
    createPost(authorName: string, content: string): Promise<{
        __kind__: "ok";
        ok: Post;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteActivity(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteActivityImage(imageId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteClanContact(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteDonationChannel(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteHelpRequest(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteManuscript(id: string): Promise<void>;
    deletePerson(id: PersonId): Promise<void>;
    deletePost(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteRelationship(id: bigint): Promise<void>;
    deleteReply(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getActivity(id: bigint): Promise<{
        __kind__: "ok";
        ok: Activity;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClanContact(id: bigint): Promise<{
        __kind__: "ok";
        ok: ClanContact;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getDonationChannel(id: bigint): Promise<{
        __kind__: "ok";
        ok: DonationChannel;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getFamilyHistory(): Promise<string>;
    getManuscript(id: string): Promise<ManuscriptEntry>;
    getPerson(id: PersonId): Promise<Person>;
    getRelationships(personId: PersonId): Promise<Array<Relationship>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listActivities(): Promise<Array<Activity>>;
    listActivityImages(activityId: bigint): Promise<Array<ActivityImage>>;
    listClanContacts(): Promise<Array<ClanContact>>;
    listDonationChannels(): Promise<Array<DonationChannel>>;
    listHelpRequests(): Promise<Array<HelpRequest>>;
    listManuscripts(): Promise<Array<ManuscriptEntry>>;
    listPeople(): Promise<Array<Person>>;
    listPosts(): Promise<Array<Post>>;
    listReplies(postId: bigint): Promise<Array<Reply>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitHelpRequest(applicantName: string, contactInfo: string, requestType: string, description: string): Promise<{
        __kind__: "ok";
        ok: HelpRequest;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateActivity(id: bigint, title: string, eventDate: string, description: string): Promise<{
        __kind__: "ok";
        ok: Activity;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateClanContact(id: bigint, contactType: string, name: string, role: string, phone: string | null, email: string | null, wechat: string | null, address: string | null, notes: string | null): Promise<{
        __kind__: "ok";
        ok: ClanContact;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateDonationChannel(id: bigint, channelName: string, accountName: string | null, accountNumber: string | null, bankName: string | null, wechatPayQr: string | null, alipayQr: string | null, instructions: string | null): Promise<{
        __kind__: "ok";
        ok: DonationChannel;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateFamilyHistory(content: string): Promise<void>;
    updateHelpRequestStatus(id: bigint, status: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updatePerson(id: PersonId, fullName: string, generationNumber: bigint, father: string, mother: string, bio: string, photo: ExternalBlob | null, gender: string | null, birthDate: string | null, deathDate: string | null, country: string | null, province: string | null, city: string | null, nationality: string | null): Promise<void>;
    uploadActivityImage(activityId: bigint, fileName: string, mimeType: string, data: Uint8Array): Promise<{
        __kind__: "ok";
        ok: ActivityImage;
    } | {
        __kind__: "err";
        err: string;
    }>;
    uploadManuscript(id: string, fileName: string, description: string, blob: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Activity as _Activity, ActivityImage as _ActivityImage, ClanContact as _ClanContact, DonationChannel as _DonationChannel, ExternalBlob as _ExternalBlob, HelpRequest as _HelpRequest, ManuscriptEntry as _ManuscriptEntry, Person as _Person, PersonId as _PersonId, Post as _Post, Reply as _Reply, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMediaFile(arg0: PersonId, arg1: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addMediaFile(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMediaFile(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addRelationship(arg0: PersonId, arg1: PersonId, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRelationship(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRelationship(arg0, arg1, arg2);
            return result;
        }
    }
    async addReply(arg0: bigint, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: Reply;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addReply(arg0, arg1, arg2);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReply(arg0, arg1, arg2);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createActivity(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: Activity;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createActivity(arg0, arg1, arg2);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createActivity(arg0, arg1, arg2);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createClanContact(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string | null, arg5: string | null, arg6: string | null, arg7: string | null): Promise<{
        __kind__: "ok";
        ok: ClanContact;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createClanContact(arg0, arg1, arg2, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7));
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClanContact(arg0, arg1, arg2, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7));
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDonationChannel(arg0: string, arg1: string | null, arg2: string | null, arg3: string | null, arg4: string | null, arg5: string | null, arg6: string | null): Promise<{
        __kind__: "ok";
        ok: DonationChannel;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createDonationChannel(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg6));
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDonationChannel(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg6));
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPerson(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: ExternalBlob | null, arg6: string | null, arg7: string | null, arg8: string | null, arg9: string | null, arg10: string | null, arg11: string | null, arg12: string | null): Promise<{
        __kind__: "ok";
        ok: PersonId;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createPerson(arg0, arg1, arg2, arg3, arg4, await to_candid_opt_n22(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg12));
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPerson(arg0, arg1, arg2, arg3, arg4, await to_candid_opt_n22(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg12));
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPost(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: Post;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1);
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1);
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteActivity(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivity(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivity(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteActivityImage(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivityImage(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivityImage(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteClanContact(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClanContact(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClanContact(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDonationChannel(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDonationChannel(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDonationChannel(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteHelpRequest(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHelpRequest(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHelpRequest(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteManuscript(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteManuscript(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteManuscript(arg0);
            return result;
        }
    }
    async deletePerson(arg0: PersonId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePerson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePerson(arg0);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteRelationship(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRelationship(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRelationship(arg0);
            return result;
        }
    }
    async deleteReply(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReply(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReply(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivity(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: Activity;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivity(arg0);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivity(arg0);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClanContact(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: ClanContact;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getClanContact(arg0);
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClanContact(arg0);
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonationChannel(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: DonationChannel;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationChannel(arg0);
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationChannel(arg0);
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFamilyHistory(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getFamilyHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFamilyHistory();
            return result;
        }
    }
    async getManuscript(arg0: string): Promise<ManuscriptEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getManuscript(arg0);
                return from_candid_ManuscriptEntry_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManuscript(arg0);
            return from_candid_ManuscriptEntry_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerson(arg0: PersonId): Promise<Person> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerson(arg0);
                return from_candid_Person_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerson(arg0);
            return from_candid_Person_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRelationships(arg0: PersonId): Promise<Array<Relationship>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelationships(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelationships(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActivities(): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivities();
            return result;
        }
    }
    async listActivityImages(arg0: bigint): Promise<Array<ActivityImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivityImages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivityImages(arg0);
            return result;
        }
    }
    async listClanContacts(): Promise<Array<ClanContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClanContacts();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClanContacts();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDonationChannels(): Promise<Array<DonationChannel>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDonationChannels();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDonationChannels();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async listHelpRequests(): Promise<Array<HelpRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listHelpRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHelpRequests();
            return result;
        }
    }
    async listManuscripts(): Promise<Array<ManuscriptEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listManuscripts();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listManuscripts();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPeople(): Promise<Array<Person>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPeople();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPeople();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPosts();
            return result;
        }
    }
    async listReplies(arg0: bigint): Promise<Array<Reply>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReplies(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReplies(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitHelpRequest(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: HelpRequest;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitHelpRequest(arg0, arg1, arg2, arg3);
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitHelpRequest(arg0, arg1, arg2, arg3);
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateActivity(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: Activity;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivity(arg0, arg1, arg2, arg3);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivity(arg0, arg1, arg2, arg3);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClanContact(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: string | null, arg6: string | null, arg7: string | null, arg8: string | null): Promise<{
        __kind__: "ok";
        ok: ClanContact;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClanContact(arg0, arg1, arg2, arg3, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg8));
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClanContact(arg0, arg1, arg2, arg3, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg8));
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDonationChannel(arg0: bigint, arg1: string, arg2: string | null, arg3: string | null, arg4: string | null, arg5: string | null, arg6: string | null, arg7: string | null): Promise<{
        __kind__: "ok";
        ok: DonationChannel;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonationChannel(arg0, arg1, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7));
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonationChannel(arg0, arg1, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7));
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFamilyHistory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFamilyHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFamilyHistory(arg0);
            return result;
        }
    }
    async updateHelpRequestStatus(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHelpRequestStatus(arg0, arg1);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHelpRequestStatus(arg0, arg1);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePerson(arg0: PersonId, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: ExternalBlob | null, arg7: string | null, arg8: string | null, arg9: string | null, arg10: string | null, arg11: string | null, arg12: string | null, arg13: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePerson(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_opt_n22(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg13));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePerson(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_opt_n22(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg13));
            return result;
        }
    }
    async uploadActivityImage(arg0: bigint, arg1: string, arg2: string, arg3: Uint8Array): Promise<{
        __kind__: "ok";
        ok: ActivityImage;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadActivityImage(arg0, arg1, arg2, arg3);
                return from_candid_variant_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadActivityImage(arg0, arg1, arg2, arg3);
            return from_candid_variant_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadManuscript(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadManuscript(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadManuscript(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ClanContact_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClanContact): ClanContact {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_DonationChannel_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonationChannel): DonationChannel {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_ManuscriptEntry_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ManuscriptEntry): Promise<ManuscriptEntry> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_Person_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Person): Promise<Person> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contactType: string;
    name: string;
    createdAt: bigint;
    role: string;
    email: [] | [string];
    address: [] | [string];
    notes: [] | [string];
    phone: [] | [string];
    wechat: [] | [string];
}): {
    id: bigint;
    contactType: string;
    name: string;
    createdAt: bigint;
    role: string;
    email?: string;
    address?: string;
    notes?: string;
    phone?: string;
    wechat?: string;
} {
    return {
        id: value.id,
        contactType: value.contactType,
        name: value.name,
        createdAt: value.createdAt,
        role: value.role,
        email: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.email)),
        address: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.address)),
        notes: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.notes)),
        phone: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.phone)),
        wechat: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.wechat))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    wechatPayQr: [] | [string];
    channelName: string;
    createdAt: bigint;
    instructions: [] | [string];
    bankName: [] | [string];
    accountName: [] | [string];
    accountNumber: [] | [string];
    alipayQr: [] | [string];
}): {
    id: bigint;
    wechatPayQr?: string;
    channelName: string;
    createdAt: bigint;
    instructions?: string;
    bankName?: string;
    accountName?: string;
    accountNumber?: string;
    alipayQr?: string;
} {
    return {
        id: value.id,
        wechatPayQr: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.wechatPayQr)),
        channelName: value.channelName,
        createdAt: value.createdAt,
        instructions: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.instructions)),
        bankName: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.bankName)),
        accountName: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.accountName)),
        accountNumber: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.accountNumber)),
        alipayQr: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.alipayQr))
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: _ExternalBlob;
    description: string;
    fileName: string;
    uploadDate: _Time;
}): Promise<{
    id: string;
    blob: ExternalBlob;
    description: string;
    fileName: string;
    uploadDate: Time;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value.blob),
        description: value.description,
        fileName: value.fileName,
        uploadDate: value.uploadDate
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PersonId;
    country: [] | [string];
    province: [] | [string];
    deathDate: [] | [string];
    birthDate: [] | [string];
    city: [] | [string];
    profilePhoto: [] | [_ExternalBlob];
    biography: string;
    generationNumber: bigint;
    fullName: string;
    siblings: Array<_PersonId>;
    nationality: [] | [string];
    children: Array<_PersonId>;
    gender: [] | [string];
    mother: string;
    mediaFiles: Array<_ExternalBlob>;
    father: string;
}): Promise<{
    id: PersonId;
    country?: string;
    province?: string;
    deathDate?: string;
    birthDate?: string;
    city?: string;
    profilePhoto?: ExternalBlob;
    biography: string;
    generationNumber: bigint;
    fullName: string;
    siblings: Array<PersonId>;
    nationality?: string;
    children: Array<PersonId>;
    gender?: string;
    mother: string;
    mediaFiles: Array<ExternalBlob>;
    father: string;
}> {
    return {
        id: value.id,
        country: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.country)),
        province: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.province)),
        deathDate: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.deathDate)),
        birthDate: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.birthDate)),
        city: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.city)),
        profilePhoto: record_opt_to_undefined(await from_candid_opt_n33(_uploadFile, _downloadFile, value.profilePhoto)),
        biography: value.biography,
        generationNumber: value.generationNumber,
        fullName: value.fullName,
        siblings: value.siblings,
        nationality: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.nationality)),
        children: value.children,
        gender: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.gender)),
        mother: value.mother,
        mediaFiles: await from_candid_vec_n34(_uploadFile, _downloadFile, value.mediaFiles),
        father: value.father
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Reply;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Reply;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Activity;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Activity;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ClanContact;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ClanContact;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ClanContact_n16(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DonationChannel;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: DonationChannel;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_DonationChannel_n20(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PersonId;
}): {
    __kind__: "ok";
    ok: PersonId;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Post;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Post;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _HelpRequest;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: HelpRequest;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ActivityImage;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ActivityImage;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClanContact>): Array<ClanContact> {
    return value.map((x)=>from_candid_ClanContact_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DonationChannel>): Array<DonationChannel> {
    return value.map((x)=>from_candid_DonationChannel_n20(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ManuscriptEntry>): Promise<Array<ManuscriptEntry>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ManuscriptEntry_n28(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Person>): Promise<Array<Person>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Person_n31(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
