/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'eventDate' : string,
}
export interface ActivityImage {
  'id' : bigint,
  'data' : Uint8Array,
  'activityId' : bigint,
  'mimeType' : string,
  'fileName' : string,
  'uploadedAt' : bigint,
}
export interface ClanContact {
  'id' : bigint,
  'contactType' : string,
  'name' : string,
  'createdAt' : bigint,
  'role' : string,
  'email' : [] | [string],
  'address' : [] | [string],
  'notes' : [] | [string],
  'phone' : [] | [string],
  'wechat' : [] | [string],
}
export interface DonationChannel {
  'id' : bigint,
  'wechatPayQr' : [] | [string],
  'channelName' : string,
  'createdAt' : bigint,
  'instructions' : [] | [string],
  'bankName' : [] | [string],
  'accountName' : [] | [string],
  'accountNumber' : [] | [string],
  'alipayQr' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface HelpRequest {
  'id' : bigint,
  'status' : string,
  'applicantName' : string,
  'contactInfo' : string,
  'createdAt' : bigint,
  'description' : string,
  'requestType' : string,
}
export interface ManuscriptEntry {
  'id' : string,
  'blob' : ExternalBlob,
  'description' : string,
  'fileName' : string,
  'uploadDate' : Time,
}
export interface Person {
  'id' : PersonId,
  'country' : [] | [string],
  'province' : [] | [string],
  'deathDate' : [] | [string],
  'birthDate' : [] | [string],
  'city' : [] | [string],
  'profilePhoto' : [] | [ExternalBlob],
  'biography' : string,
  'generationNumber' : bigint,
  'fullName' : string,
  'siblings' : Array<PersonId>,
  'nationality' : [] | [string],
  'children' : Array<PersonId>,
  'gender' : [] | [string],
  'mother' : string,
  'mediaFiles' : Array<ExternalBlob>,
  'father' : string,
}
export type PersonId = bigint;
export interface Post {
  'id' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'authorName' : string,
}
export interface Relationship {
  'id' : bigint,
  'createdAt' : Time,
  'person1Id' : PersonId,
  'person2Id' : PersonId,
  'relationshipType' : string,
}
export interface Reply {
  'id' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'postId' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMediaFile' : ActorMethod<
    [PersonId, ExternalBlob],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addRelationship' : ActorMethod<[PersonId, PersonId, string], undefined>,
  'addReply' : ActorMethod<
    [bigint, string, string],
    { 'ok' : Reply } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createActivity' : ActorMethod<
    [string, string, string],
    { 'ok' : Activity } |
      { 'err' : string }
  >,
  'createClanContact' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    { 'ok' : ClanContact } |
      { 'err' : string }
  >,
  'createDonationChannel' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    { 'ok' : DonationChannel } |
      { 'err' : string }
  >,
  'createPerson' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    { 'ok' : PersonId }
  >,
  'createPost' : ActorMethod<
    [string, string],
    { 'ok' : Post } |
      { 'err' : string }
  >,
  'deleteActivity' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteActivityImage' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteClanContact' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteDonationChannel' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteHelpRequest' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteManuscript' : ActorMethod<[string], undefined>,
  'deletePerson' : ActorMethod<[PersonId], undefined>,
  'deletePost' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'deleteRelationship' : ActorMethod<[bigint], undefined>,
  'deleteReply' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'getActivity' : ActorMethod<
    [bigint],
    { 'ok' : Activity } |
      { 'err' : string }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClanContact' : ActorMethod<
    [bigint],
    { 'ok' : ClanContact } |
      { 'err' : string }
  >,
  'getDonationChannel' : ActorMethod<
    [bigint],
    { 'ok' : DonationChannel } |
      { 'err' : string }
  >,
  'getFamilyHistory' : ActorMethod<[], string>,
  'getManuscript' : ActorMethod<[string], ManuscriptEntry>,
  'getPerson' : ActorMethod<[PersonId], Person>,
  'getRelationships' : ActorMethod<[PersonId], Array<Relationship>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActivities' : ActorMethod<[], Array<Activity>>,
  'listActivityImages' : ActorMethod<[bigint], Array<ActivityImage>>,
  'listClanContacts' : ActorMethod<[], Array<ClanContact>>,
  'listDonationChannels' : ActorMethod<[], Array<DonationChannel>>,
  'listHelpRequests' : ActorMethod<[], Array<HelpRequest>>,
  'listManuscripts' : ActorMethod<[], Array<ManuscriptEntry>>,
  'listPeople' : ActorMethod<[], Array<Person>>,
  'listPosts' : ActorMethod<[], Array<Post>>,
  'listReplies' : ActorMethod<[bigint], Array<Reply>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitHelpRequest' : ActorMethod<
    [string, string, string, string],
    { 'ok' : HelpRequest } |
      { 'err' : string }
  >,
  'updateActivity' : ActorMethod<
    [bigint, string, string, string],
    { 'ok' : Activity } |
      { 'err' : string }
  >,
  'updateClanContact' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    { 'ok' : ClanContact } |
      { 'err' : string }
  >,
  'updateDonationChannel' : ActorMethod<
    [
      bigint,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    { 'ok' : DonationChannel } |
      { 'err' : string }
  >,
  'updateFamilyHistory' : ActorMethod<[string], undefined>,
  'updateHelpRequestStatus' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updatePerson' : ActorMethod<
    [
      PersonId,
      string,
      bigint,
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'uploadActivityImage' : ActorMethod<
    [bigint, string, string, Uint8Array],
    { 'ok' : ActivityImage } |
      { 'err' : string }
  >,
  'uploadManuscript' : ActorMethod<
    [string, string, string, ExternalBlob],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];