/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PersonId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Reply = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'postId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'eventDate' : IDL.Text,
});
export const ClanContact = IDL.Record({
  'id' : IDL.Nat,
  'contactType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'wechat' : IDL.Opt(IDL.Text),
});
export const DonationChannel = IDL.Record({
  'id' : IDL.Nat,
  'wechatPayQr' : IDL.Opt(IDL.Text),
  'channelName' : IDL.Text,
  'createdAt' : IDL.Int,
  'instructions' : IDL.Opt(IDL.Text),
  'bankName' : IDL.Opt(IDL.Text),
  'accountName' : IDL.Opt(IDL.Text),
  'accountNumber' : IDL.Opt(IDL.Text),
  'alipayQr' : IDL.Opt(IDL.Text),
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const ManuscriptEntry = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'uploadDate' : Time,
});
export const Person = IDL.Record({
  'id' : PersonId,
  'country' : IDL.Opt(IDL.Text),
  'province' : IDL.Opt(IDL.Text),
  'deathDate' : IDL.Opt(IDL.Text),
  'birthDate' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'biography' : IDL.Text,
  'generationNumber' : IDL.Nat,
  'fullName' : IDL.Text,
  'siblings' : IDL.Vec(PersonId),
  'nationality' : IDL.Opt(IDL.Text),
  'children' : IDL.Vec(PersonId),
  'gender' : IDL.Opt(IDL.Text),
  'mother' : IDL.Text,
  'mediaFiles' : IDL.Vec(ExternalBlob),
  'father' : IDL.Text,
});
export const Relationship = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'person1Id' : PersonId,
  'person2Id' : PersonId,
  'relationshipType' : IDL.Text,
});
export const ActivityImage = IDL.Record({
  'id' : IDL.Nat,
  'data' : IDL.Vec(IDL.Nat8),
  'activityId' : IDL.Nat,
  'mimeType' : IDL.Text,
  'fileName' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const HelpRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'applicantName' : IDL.Text,
  'contactInfo' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'requestType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMediaFile' : IDL.Func(
      [PersonId, ExternalBlob],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addRelationship' : IDL.Func([PersonId, PersonId, IDL.Text], [], []),
  'addReply' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Reply, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createActivity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Activity, 'err' : IDL.Text })],
      [],
    ),
  'createClanContact' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : ClanContact, 'err' : IDL.Text })],
      [],
    ),
  'createDonationChannel' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : DonationChannel, 'err' : IDL.Text })],
      [],
    ),
  'createPerson' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : PersonId })],
      [],
    ),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Post, 'err' : IDL.Text })],
      [],
    ),
  'deleteActivity' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteActivityImage' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteClanContact' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteDonationChannel' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteHelpRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteManuscript' : IDL.Func([IDL.Text], [], []),
  'deletePerson' : IDL.Func([PersonId], [], []),
  'deletePost' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteRelationship' : IDL.Func([IDL.Nat], [], []),
  'deleteReply' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getActivity' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : Activity, 'err' : IDL.Text })],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClanContact' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : ClanContact, 'err' : IDL.Text })],
      ['query'],
    ),
  'getDonationChannel' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : DonationChannel, 'err' : IDL.Text })],
      ['query'],
    ),
  'getFamilyHistory' : IDL.Func([], [IDL.Text], ['query']),
  'getManuscript' : IDL.Func([IDL.Text], [ManuscriptEntry], ['query']),
  'getPerson' : IDL.Func([PersonId], [Person], ['query']),
  'getRelationships' : IDL.Func([PersonId], [IDL.Vec(Relationship)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'listActivityImages' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ActivityImage)],
      ['query'],
    ),
  'listClanContacts' : IDL.Func([], [IDL.Vec(ClanContact)], ['query']),
  'listDonationChannels' : IDL.Func([], [IDL.Vec(DonationChannel)], ['query']),
  'listHelpRequests' : IDL.Func([], [IDL.Vec(HelpRequest)], ['query']),
  'listManuscripts' : IDL.Func([], [IDL.Vec(ManuscriptEntry)], ['query']),
  'listPeople' : IDL.Func([], [IDL.Vec(Person)], ['query']),
  'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'listReplies' : IDL.Func([IDL.Nat], [IDL.Vec(Reply)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitHelpRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : HelpRequest, 'err' : IDL.Text })],
      [],
    ),
  'updateActivity' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Activity, 'err' : IDL.Text })],
      [],
    ),
  'updateClanContact' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : ClanContact, 'err' : IDL.Text })],
      [],
    ),
  'updateDonationChannel' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : DonationChannel, 'err' : IDL.Text })],
      [],
    ),
  'updateFamilyHistory' : IDL.Func([IDL.Text], [], []),
  'updateHelpRequestStatus' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updatePerson' : IDL.Func(
      [
        PersonId,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'uploadActivityImage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Variant({ 'ok' : ActivityImage, 'err' : IDL.Text })],
      [],
    ),
  'uploadManuscript' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PersonId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Reply = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'postId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'eventDate' : IDL.Text,
  });
  const ClanContact = IDL.Record({
    'id' : IDL.Nat,
    'contactType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'wechat' : IDL.Opt(IDL.Text),
  });
  const DonationChannel = IDL.Record({
    'id' : IDL.Nat,
    'wechatPayQr' : IDL.Opt(IDL.Text),
    'channelName' : IDL.Text,
    'createdAt' : IDL.Int,
    'instructions' : IDL.Opt(IDL.Text),
    'bankName' : IDL.Opt(IDL.Text),
    'accountName' : IDL.Opt(IDL.Text),
    'accountNumber' : IDL.Opt(IDL.Text),
    'alipayQr' : IDL.Opt(IDL.Text),
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const ManuscriptEntry = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'uploadDate' : Time,
  });
  const Person = IDL.Record({
    'id' : PersonId,
    'country' : IDL.Opt(IDL.Text),
    'province' : IDL.Opt(IDL.Text),
    'deathDate' : IDL.Opt(IDL.Text),
    'birthDate' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'biography' : IDL.Text,
    'generationNumber' : IDL.Nat,
    'fullName' : IDL.Text,
    'siblings' : IDL.Vec(PersonId),
    'nationality' : IDL.Opt(IDL.Text),
    'children' : IDL.Vec(PersonId),
    'gender' : IDL.Opt(IDL.Text),
    'mother' : IDL.Text,
    'mediaFiles' : IDL.Vec(ExternalBlob),
    'father' : IDL.Text,
  });
  const Relationship = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'person1Id' : PersonId,
    'person2Id' : PersonId,
    'relationshipType' : IDL.Text,
  });
  const ActivityImage = IDL.Record({
    'id' : IDL.Nat,
    'data' : IDL.Vec(IDL.Nat8),
    'activityId' : IDL.Nat,
    'mimeType' : IDL.Text,
    'fileName' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const HelpRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'applicantName' : IDL.Text,
    'contactInfo' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'requestType' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMediaFile' : IDL.Func(
        [PersonId, ExternalBlob],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addRelationship' : IDL.Func([PersonId, PersonId, IDL.Text], [], []),
    'addReply' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Reply, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createActivity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Activity, 'err' : IDL.Text })],
        [],
      ),
    'createClanContact' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : ClanContact, 'err' : IDL.Text })],
        [],
      ),
    'createDonationChannel' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : DonationChannel, 'err' : IDL.Text })],
        [],
      ),
    'createPerson' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : PersonId })],
        [],
      ),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Post, 'err' : IDL.Text })],
        [],
      ),
    'deleteActivity' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteActivityImage' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteClanContact' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteDonationChannel' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteHelpRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteManuscript' : IDL.Func([IDL.Text], [], []),
    'deletePerson' : IDL.Func([PersonId], [], []),
    'deletePost' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteRelationship' : IDL.Func([IDL.Nat], [], []),
    'deleteReply' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getActivity' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : Activity, 'err' : IDL.Text })],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClanContact' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : ClanContact, 'err' : IDL.Text })],
        ['query'],
      ),
    'getDonationChannel' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : DonationChannel, 'err' : IDL.Text })],
        ['query'],
      ),
    'getFamilyHistory' : IDL.Func([], [IDL.Text], ['query']),
    'getManuscript' : IDL.Func([IDL.Text], [ManuscriptEntry], ['query']),
    'getPerson' : IDL.Func([PersonId], [Person], ['query']),
    'getRelationships' : IDL.Func(
        [PersonId],
        [IDL.Vec(Relationship)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'listActivityImages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ActivityImage)],
        ['query'],
      ),
    'listClanContacts' : IDL.Func([], [IDL.Vec(ClanContact)], ['query']),
    'listDonationChannels' : IDL.Func(
        [],
        [IDL.Vec(DonationChannel)],
        ['query'],
      ),
    'listHelpRequests' : IDL.Func([], [IDL.Vec(HelpRequest)], ['query']),
    'listManuscripts' : IDL.Func([], [IDL.Vec(ManuscriptEntry)], ['query']),
    'listPeople' : IDL.Func([], [IDL.Vec(Person)], ['query']),
    'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'listReplies' : IDL.Func([IDL.Nat], [IDL.Vec(Reply)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitHelpRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : HelpRequest, 'err' : IDL.Text })],
        [],
      ),
    'updateActivity' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Activity, 'err' : IDL.Text })],
        [],
      ),
    'updateClanContact' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : ClanContact, 'err' : IDL.Text })],
        [],
      ),
    'updateDonationChannel' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : DonationChannel, 'err' : IDL.Text })],
        [],
      ),
    'updateFamilyHistory' : IDL.Func([IDL.Text], [], []),
    'updateHelpRequestStatus' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updatePerson' : IDL.Func(
        [
          PersonId,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'uploadActivityImage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Variant({ 'ok' : ActivityImage, 'err' : IDL.Text })],
        [],
      ),
    'uploadManuscript' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };